spring:
  datasource:
    url: jdbc:h2:file:~/.harmony/kindless
    username: root
    password: null
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enable: true
logging:
  level:
    org.springframework.web.client: debug
    com.harmony.kindless.http.client: debug