debug: true
server:
  context-path: /
spring:
  datasource:
    url: jdbc:h2:file:~/.harmony/kindless
    username: root
    password: null
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      path: /h2
      enabled: true
#management:
#  context-path: /manage
#  security:
#    enabled: false
#logging:
#  level:
#    org.springframework.web.client: debug
#    com.harmony.kindless.http.client: debug
harmony:
  cfg:
    properties:
      show-info: true
