debug: true
server:
  port: 9000
  servlet:
    context-path: /
spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:h2:file:~/.harmony/kindless
#    username: root
#    password: null
  datasource:
    druid:
      url: jdbc:h2:file:~/.harmony/kindless
      username: root
      password: null
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create # create, create-drop, update, validate
    show-sql: true
  h2:
    console:
      path: /h2
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#eureka:
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    service-url: 
#      defaultZone: http://localhost:${server.port}/eureka/
#shiro:
#  enabled: false
#  web:
#    enabled: false
#management:
#  context-path: /manage
#  security:
#    enabled: false
#logging:
#  level:
#    org.springframework.web.client: debug
#    com.harmony.kindless.http.client: debug
harmony:
  app:
    properties:
      scan-async: false
      show-info: true
