server:
  context-path: /
  port: 9000
spring:
  datasource:
    url: jdbc:h2:file:~/.harmony/kindless
    username: root
    password: null
  jpa:
    hibernate:
      ddl-auto: update # create, create-drop, update, validate
    show-sql: true
  h2:
    console:
      path: /h2
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#shiro:
#  enabled: false
#  web:
#    enabled: false
#management:
#  context-path: /manage
#  security:
#    enabled: false
#logging:
#  level:
#    org.springframework.web.client: debug
#    com.harmony.kindless.http.client: debug
harmony:
  cfg:
    properties:
      scan-async: false
      show-info: true
