#debug: true
server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/moment?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: null
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: none # create, create-drop, update, validate
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:
  level:
    org.hibernate.SQL: debug
harmony:
  app:
    properties:
      scan-async: false
      show-info: true
