debug: true
#eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#    lease-expiration-duration-in-seconds: 120
#    lease-renewal-interval-in-seconds: 60
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: kindless-gateway
  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
    gateway:
      routes:
        - id: kindless-core
          uri: lb://kindless-core
          predicates:
            - Path=/user/**
        - id: kindless-moment
          uri: lb://kindless-moment
          predicates:
            - Path=/moment/**
            - Path=/moments/**
management:
  endpoints:
    web.exposure.include: '*'
  endpoint:
    shutdown.enabled: true